### ISSUE TITLE
Cannot change column type in project table view

### ISSUE THREAD

**Issue by JordanChoe** [marcusolsson/obsidian-projects#409] opened 2023-01-26 14:43 UTC
### What happened?

I can't change the column type in the project column view.  This requires me to create a db folder view to make these edits.  I'm unsure if this is by design or a bug?

### What did you expect to happen?

I expected that when selecting the type under configure field that the drop down would allow me to change to a select or other property. I attempted to add some default values to see if that would trigger the drop down, and it had no effect.

### How can we reproduce it (as minimally and precisely as possible)?

Load a project, I am using the same sample budget project created for other issue(s).  Select the three dots and then configure field.  nothing happens when clicking the text drop down.  
![Screenshot (75)](https://user-images.githubusercontent.com/108248499/214865057-fac30b84-d218-4e98-af7c-9a13496c301a.png)
![Screenshot (76)](https://user-images.githubusercontent.com/108248499/214865065-fba73c19-e3fe-4ee4-bd94-f237bd7d3f8c.png)

### Plugin version

1.11.5

### Obsidian version

1.1.9

### OS

Windows

**Comment by marcusolsson** [comment] 2023-01-26 14:58
Changing column type isn't supported yet. Sounds like a duplicate of #320?

**Comment by JordanChoe** [comment] 2023-01-26 15:44
Thanks.  I'll get better at search keywords before posting. :)

**Comment by marcusolsson** [comment] 2023-01-26 15:54
No worries. I'd prefer to err on the side of duplicates rather than losing out on a bug report 😄

**Closed by marcusolsson** 2023-01-26 15:54 UTC
Labels: triage/duplicate, kind/feature
