### ISSUE TITLE
I cannot rearrange the cards on the board

### ISSUE THREAD

**Issue by GeneralKugelBlitz** [marcusolsson/obsidian-projects#652] opened 2023-08-08 16:42 UTC
### What happened?

When I try to rearrange cards on board, they just snap back to where they like to be and it wasn't like they were doing it in order of due date either. Please fix this. Thank you.

### What did you expect to happen?

That I can snap the board to whatever place I want or they are sorted relative to due date etc

### How can we reproduce it (as minimally and precisely as possible)?

just try rearranging a board

### Plugin version

1.16.3

### Obsidian version

1.3.7

### OS

Windows

**Comment by beatblender** [comment] 2023-08-25 09:11
(Same on MacOS.)

**Comment by savvyslog** [comment] 2023-08-29 23:49
I'm also having this same issue. 

Related to (and perhaps causing) this issue is the fact that _there is no longer any Priority dropdown selection_ available in the Board view. So if the plugin doesn't know which frontmatter key to use to track lane order, it makes sense that you then can't actually customize the lane order...

I tried uninstalling and reinstalling the plugin, as well as installing it in a new vault, but the issue still persists, even with the provided demo project.

**Comment by Acylation** [comment] 2023-09-06 16:52
Closing as duplicate of #586 .

Sorry for the inconvenience, but we introduced this breaking change in #584 to simplify the maintaining. New method for manully sorting needs some design.

**Closed by Acylation** 2023-09-06 16:52 UTC
Labels: kind/bug, needs-triage

**Comment by pdfrod** [comment] 2023-10-19 13:39
Hi @Acylation. This issue was closed as duplicate of https://github.com/marcusolsson/obsidian-projects/issues/586 but that one is also closed. Does that mean there are no plans to solve this problem?

**Comment by Acylation** [comment] 2023-10-24 18:40
@pdfrod Thanks for your input. Shor answer would be nope.

In-column reorder is requested and echoed by many, as recorded in that thread. Closing this and linking to the earlier one aims to integrate related discussions and thoughts. Though #586 is closed as the question is answered, it does not imply that we won't work on the feature.

To make that thread clear for search and keeping the disscussions, I'd like to leave it as is, and create a new FR pointing to it when I have the capacity to work on this. Please note that won't be earlier than December.
