### ISSUE TITLE
Priority selector for Board is missing - and cant sort by priority

### ISSUE THREAD

**Issue by dakota-marshall** [marcusolsson/obsidian-projects#627] opened 2023-07-19 20:56 UTC
### What happened?

When viewing the project in the board view, the 'priorty' field selector is missing, and I am unable to sort my entries by their priority, moving one around causes it to snap back to where it was before I moved it:

My actual vault
![image](https://github.com/marcusolsson/obsidian-projects/assets/88565818/492ec9a6-5af9-4d3f-8edc-10995d40bf6a)

A brand new test vault with nothing installed but projects:
![image](https://github.com/marcusolsson/obsidian-projects/assets/88565818/6acf72f9-1b27-45ff-a694-52abdf024ab3)

### What did you expect to happen?

The priority selector to be present and allow me to sort by said priority

### How can we reproduce it (as minimally and precisely as possible)?

- Create new vault
- Install Projects plugin
- Create new project folder and add create new project from that folder
- Create board view
- Create test note with following front matter

```
---
prio: 1
status: testing
---
```

- The status selector is there, but not priority

### Plugin version

1.16.3

### Obsidian version

1.3.5

### OS

Linux

**Comment by marcusolsson** [comment] 2023-07-21 17:12
Closing as duplicate of #586.

**Closed by marcusolsson** 2023-07-21 17:12 UTC
Labels: kind/bug, needs-triage
