### ISSUE TITLE
Load issue on iPhone 12

### ISSUE THREAD

**Issue by metamole** [marcusolsson/obsidian-projects#261] opened 2022-12-24 12:01 UTC
### What happened?

Plugin installs but will not enable. Works fine on iPad OS and macOS

### What did you expect to happen?

Plug-in to install and work as expected

### How can we reproduce it (as minimally and precisely as possible)?

Try to install on a device. I had already installed on other devices and it worked well

### Anything else we need to know?

I've uninstalled, closed obsidian, reloaded obsidian and tried again. Issue was not resolved

### Plugin version

1.6.1

### Obsidian version

1.4.1(83)

### OS

Other

**Comment by marcusolsson** [comment] 2022-12-25 12:57
> Works fine on iPad OS and macOS

Interesting, otherwise I'd say this issue is a duplicate of #212.

**Comment by marcusolsson** [comment] 2022-12-26 16:49
Closing in favor of #161.

**Closed by marcusolsson** 2022-12-26 16:49 UTC
Labels: kind/bug, triage/accepted, os/ios
