### ISSUE TITLE
Combined Calendar View

### ISSUE THREAD

**Issue by HoXuanOz** [marcusolsson/obsidian-projects#268] opened 2022-12-27 00:35 UTC
### What would you like to be added?

I will be having multiple projects, with each project having multiple notes and/or Dates.

It would be great to have a feature to be able to have a calendar view where I can see all due dates from each calendar on 1 calendar view.

### Why is this needed?

The ability to view ALL tasks due on a particular date would be a convenient and efficient way of quickly seeing my total workload for the required period.

Thanks

**Comment by marcusolsson** [comment] 2022-12-27 09:44
Duplicate of #140.

**Closed by marcusolsson** 2022-12-27 09:44 UTC
Labels: kind/feature, needs-triage
