### ISSUE TITLE
Open on mobile

### ISSUE THREAD

**Issue by Asetnozama** [marcusolsson/obsidian-projects#207] opened 2022-11-24 17:48 UTC
### What would you like help with?

Hello,

Could somebody please explain to me how to enable this awesome plugin on mobile?

Thank you in advance!!

**Comment by laawn** [comment] 2022-11-25 14:53
I also can't enable it on mobile, despite the update stating mobile enabled.

**Comment by marcusolsson** [comment] 2022-11-27 00:15
Hm. I thought all you needed to do was to set [isDesktopOnly](https://github.com/marcusolsson/obsidian-projects/blob/582808b0940ff129838b87866208736d6dade39b/manifest.json#L9) to false. I'll try and install the mobile app and test it myself.

**Comment by caseyg** [comment] 2022-11-28 18:34
I posted about the same issue here: https://github.com/marcusolsson/obsidian-projects/pull/199#issuecomment-1329558695

and #199 also looks like a duplicate.

**Comment by marcusolsson** [comment] 2022-12-04 22:49
Closing as duplicate of #212

**Closed by marcusolsson** 2022-12-04 22:49 UTC
Labels: kind/support, needs-triage, os/ios
