### ISSUE TITLE
Number field comparison doesn't work for value of 0

### ISSUE THREAD

**Issue by amymelody** [marcusolsson/obsidian-projects#806] opened 2024-03-08 19:12 UTC
### What happened?

I have a Project with a Number field "priority". In a Board view I tried to apply a color filter that checks that "priority" <= 0. It did not apply the color to any of my notes with "priority" = 0. I tried other comparisons to see if I could get those notes to be colored.

Comparisons that _did_ apply color to notes with priority 0 as expected were:
- priority == 0
- priority != 1

Comparisons that _did not_ apply color to notes with priority 0 were:
- priority <= 0
- priority >= 0
- priority < 1
- priority > -1

Comparisons mostly worked as expected for notes with nonzero priority, _except_ when comparing to 0.

![Screenshot 2024-03-08 110314](https://github.com/marcusolsson/obsidian-projects/assets/3280588/d3884230-e999-4e26-b50f-439a2a1cef11)

### What did you expect to happen?

I expected notes with priority 0 to be colored when applying these comparisons:
- priority <= 0
- priority >= 0
- priority < 1
- priority > -1

I expected notes with nonzero priority to be colored when checking for priority greater than or less than 0.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create new project
2. Add a new note to the project
3. Add a Number field (e.g. "priority") to the new note, with a value of 0
4. Add a color for the current view of the project, with the condition `priority >= 0`
5. Observe that the note is not colored

### Plugin version

1.17.1

### Obsidian version

1.5.8

### OS

Windows

**Comment by Acylation** [comment] 2024-03-09 05:12
Yes this is recognized and solved in #787 but not yet released. You can see that fixed in the next version. Sorry that I've been trapped in another plugin for a while but will soon return to make improvements on Projects.

Mark as duplicate of #786 and solved by #787.

**Closed by Acylation** 2024-03-09 05:12 UTC
Labels: kind/bug, triage/confirmed
