### ISSUE TITLE
[FR] CSV Support

### ISSUE THREAD

**Issue by yurijserrano** [marcusolsson/obsidian-projects#203] opened 2022-11-24 03:25 UTC
### What would you like to be added?

Good Evening @marcusolsson 

I hope you are well

That the plugin supports not only displaying the data present in the folders (notes) but also the data present in CSV files.

### Why is this needed?

Because many users end up having a lot of data in CSV files and instead of having to include all this data in the Vault, it would be easier to read the CSV and show the data so that it can be edited directly in the file or also supporting adding new data into the CSV file.

**Comment by marcusolsson** [comment] 2022-11-26 23:53
I'm closing this as a duplicate of #77 (my response is the same of in that issue).

**Closed by marcusolsson** 2022-11-26 23:53 UTC
Labels: triage/duplicate, kind/feature
