### ISSUE TITLE
Export table to CSV

### ISSUE THREAD

**Issue by FavorOfTheWater** [marcusolsson/obsidian-projects#920] opened 2024-07-10 16:33 UTC
### What would you like to be added?

If there's any way there could be a function to either export a the table view to a CSV file or even just the ability to copy/paste into Excel (or similar), this would be the godsend of all godsend plugins. 

Also a note: I'm terrible with computer science so Obsidian has been a fun challenge so far (currently configuring it to support my office), and I just wanted to let you know how much I appreciate Projects, even without the export function. I was desperate to find some way to convert properties into a table of contact information/data, so imagine my relief when I enabled the plugin and only had to rearrange the fields! So thank you so much for all the work you do.

### Why is this needed?

Much of what I do (along with, I'm sure, many others) involves mail merges, and the ability to compile my data is already very, very helpful. That said, it's pretty much stuck with me, on my computer screen, and I can't do much with the view provided. It could be a desktop-only feature, it could be a copy/paste function so that I could move my table to Excel or even word- I just need the ability to work with my information the _tiniest_ bit more.

**Comment by Acylation** [comment] 2024-07-18 16:15
Thanks for sharing your case! Close this as a duplicate of #318, and will add this in the following iterations.

**Closed by Acylation** 2024-07-18 16:15 UTC
Labels: kind/feature, needs-triage
