### ISSUE TITLE
Board views should display fields like tags, images, dates and other custom fields

### ISSUE THREAD

**Issue by ChristianLempa** [marcusolsson/obsidian-projects#260] opened 2022-12-24 09:32 UTC
### What would you like to be added?

When using Board view, we should be able to see fields like tags, images, dates and other custom fields. I'd like to have it optional so that you can enable or disable, which fields should be visible in the preview.

### Why is this needed?

This will enhance the UX, when working with Board Views, to quickly identify which items are on due date, what are the tags for the board items, etc.

**Comment by marcusolsson** [comment] 2022-12-26 16:54
Thanks for reporting! Closing as duplicate of #53.

**Closed by marcusolsson** 2022-12-26 16:54 UTC
Labels: triage/duplicate, kind/feature
