### ISSUE TITLE
I cant change data types

### ISSUE THREAD

**Issue by As-Design18** [marcusolsson/obsidian-projects#558] opened 2023-05-11 06:45 UTC
### What happened?

I created a table but all my columns are displayed as text and i am not able to change the datatype. There is a little text which says "changing datatype is not supported yet" but i saw many others using it. What is the problem? 
<img width="562" alt="Bildschirmfoto 2023-05-11 um 08 43 50" src="https://github.com/marcusolsson/obsidian-projects/assets/117035403/80371881-86a7-41e3-a821-03f2ba976a1b">

### What did you expect to happen?

I want to change the datatype according to the data i am inserting e.g Date, Tags etc. 

### How can we reproduce it (as minimally and precisely as possible)?

Just create a table and try to change the datatype 

### Plugin version

1.15.3

### Obsidian version

1.2.8

### OS

macOS

**Comment by Acylation** [comment] 2023-05-11 11:55
Related topics:
- #320 
- #409

**Comment by marcusolsson** [comment] 2023-05-11 14:52
I should really change the dropdown to a text label at this point 😓 I was hoping that I'd be able to add this feature shortly after adding the Configure field modal.

I'm marking this as a duplicate of #320 for now.

**Closed by marcusolsson** 2023-05-11 14:52 UTC
Labels: kind/bug, needs-triage
