### ISSUE TITLE
0.17.9 some buttons overlap with page headers buttons

### ISSUE THREAD

**Issue by danieltomasz** [marcusolsson/obsidian-projects#57] opened 2022-10-13 15:14 UTC
I use commander  plugin with  additional page header buttons.
Now since the 0.17.9 release I see of overlap between these buttons, "more option buttons", and the  plugin buttons (new and type of view buttons) especially when the pane is narrow.

In 0.17.8 I didn't observed this  effect, as the plugin buttons were "one level" below page headers.

**Comment by marcusolsson** [comment] 2022-10-13 15:25
Hm. I don't know what could've affected this between these two version. Would you be able to share a before and after screenshot?

**Comment by marcusolsson** [comment] 2022-10-13 15:28
I tried installing the Commander plugin and added a couple of Page Header commands. Looks alright to me?

<img width="373" alt="CleanShot 2022-10-13 at 17 27 47@2x" src="https://user-images.githubusercontent.com/8396880/195639557-c2d05e3b-e845-4487-8307-f200801bb122.png">

**Comment by marcusolsson** [comment] 2022-10-14 07:08
I've confirmed this with the Shimmering Focus theme, but since it seems to be specific to that theme, I'm not sure how much we can do here. Closing this for now.

**Closed by marcusolsson** 2022-10-14 07:08 UTC
