### ISSUE TITLE
Ability to add any Note within the vault as a View

### ISSUE THREAD

**Issue by thecheesemo** [marcusolsson/obsidian-projects#436] opened 2023-02-22 17:19 UTC
### What would you like to be added?

Please forgive me if this already been asked for. I didn't see it in the issues.

I would like to add specific notes to my Projects. Essentially, this would simply add a view that is another note within the vault. This would be different from opening up a different note in two ways. (see my amateur mock up below)

1. There would be a button to open the note along side the other view buttons. 

2. The top "navigation bar" of the Projects plugin would remain at the top, Maybe there could even be a toggle for Reading/Editing view

![mockup](https://user-images.githubusercontent.com/65478777/220706066-c555b288-fbb9-4b6a-8dfe-6dca9ec82eff.png)

### Why is this needed?

This would make for an extremely flexible addition to my projects. It would allow me to being in other elements of my project management workflow to be more easily accessible from within the Projects Plugin.

**Comment by marcusolsson** [comment] 2023-03-15 11:51
This seems to be a duplicate of #375. Let me know if not, and I'll open it back up.

**Closed by marcusolsson** 2023-03-15 11:51 UTC
Labels: kind/feature, needs-triage

**Comment by thecheesemo** [comment] 2023-03-18 17:23
Agreed. I looked for similar posts, but I clearly missed that one. Thank you.
