### ISSUE TITLE
Support inline attributes

### ISSUE THREAD

**Issue by chenxin0397** [marcusolsson/obsidian-projects#70] opened 2022-10-27 04:34 UTC
Show Project can only display this format

```
---
status: Backlog
due: 2022-11-03
published: false
weight: 45
tags:
- pkm
- obsidian
---
```

This format cannot be displayed:
```
status:: Backlog
due:: 2022-11-03
published::false
weight::45
tags::
- pkm
- obsidian
```

**Comment by marcusolsson** [comment] 2022-10-27 08:00
AFAIK, inline attributes is a Dataview-specific syntax. If you have Dataview enabled, you can create projects from Dataview queries. Then you should be able to query the inline attributes. Let me know if not!

**Comment by chenxin0397** [comment] 2022-10-27 10:47
how can i should be able to query the inline attributes.?

**Comment by chenxin0397** [comment] 2022-10-27 11:25
I am indeed using the Dataview plugin, because for a long time some files needed two colons to add YAML content, so now there are nearly 200 files with only this content:
```
状态:: 已安装
Pid:: obsidian-double-click-tab
类型:: 标签页
日期:: 2022-10-18
tags:: #插件记录
作者:: Boninall
安装版本:: 1.1.2
功能介绍:: 用于在双击选项卡标题（如关闭选项卡）时修改默认行为。
仓库网址:: https://github.com/Quorafind/Obsidian-Double-Click-Tab
aliases:: 双击标签页
我的评价::
删除原因:: 
```
When I wanted to use the Project plugin for management, I found that the effect was not good, and some Chinese content could not be displayed

**Comment by marcusolsson** [comment] 2022-10-27 11:50
Can you share the Dataview query you're using so I can try reproducing the issue?

**Comment by chenxin0397** [comment] 2022-10-27 12:34
---
aliases: 
tags: 管理页面 DW
created: 2022-10-26 10:04:11
modified: 2022-10-26 10:09:40
obsidianUIMode: preview
---

```dataview
table without id
状态,
类型,
file.link as 文件,
Pid as ID, 
日期,
status,
功能介绍
from #插件记录
where !contains(file.name, "模板-插件记录")
sort 日期 desc
```

**Comment by chenxin0397** [comment] 2022-10-27 12:34
Oh, yes, there is one more thing, that is, there seems to be incompatibility in the way tags are written. If there are files in the same project table, it is written like this:
tags:
- pkm
- obsidian

Other files are written like this:
tags: pkm obsidian
The tags in the project table will only show the latter

**Comment by marcusolsson** [comment] 2022-10-27 12:46
I added a file called "Issue 70" and created a new project with the query you provided:

![CleanShot 2022-10-27 at 14 41 57@2x](https://user-images.githubusercontent.com/8396880/198287162-93f386be-d14a-4b8a-8640-e48c2b33cea6.png)

<img width="574" alt="CleanShot 2022-10-27 at 14 44 05@2x" src="https://user-images.githubusercontent.com/8396880/198287500-0ddff1b4-c7b0-4b18-8cb5-528b612c39ee.png">

It seems to work as intended? Could you confirm that you're enabling Dataview when you create your project?

**Comment by marcusolsson** [comment] 2022-10-27 12:55
Regarding the way tags are being displayed. 

Each column has a data type. When the plugin reads the files, it tries to detect the data type based on the field values. Currently, if the plugin detects multiple different data types, it falls back to a string field. 

In your example, it seems like you have a file that says:

```yaml
tags:
- pkm
- obsidian
```

and another that says:

```yaml
tags: pkm obsidian
```

Since the `tags` property has both an array value, and a text value, it falls back to a text field. The reason the other cells are empty is because the plugin doesn't know how to convert the array into a string. In a future version, I'd like to show parsing error in a user-friendly way.

Could you share what you'd expect to happen in this case?

**Comment by chenxin0397** [comment] 2022-10-27 15:05
![image](https://user-images.githubusercontent.com/73974352/198326877-9d503662-fc21-4e0c-8bec-88eb464cb350.png)
Why is my UI content different here?

**Comment by chenxin0397** [comment] 2022-10-27 15:09
> Regarding the way tags are being displayed.
> 
> Each column has a data type. When the plugin reads the files, it tries to detect the data type based on the field values. Currently, if the plugin detects multiple different data types, it falls back to a string field.
> 
> In your example, it seems like you have a file that says:
> 
> ```yaml
> tags:
> - pkm
> - obsidian
> ```
> 
> and another that says:
> 
> ```yaml
> tags: pkm obsidian
> ```
> 
> Since the `tags` property has both an array value, and a text value, it falls back to a text field. The reason the other cells are empty is because the plugin doesn't know how to convert the array into a string. In a future version, I'd like to show parsing error in a user-friendly way.
> 
> Could you share what you'd expect to happen in this case?

I hope that both ways of writing can be displayed. It doesn't matter whether there is a difference in display effect, but it is mainly for the convenience of reading the data content.

**Comment by marcusolsson** [comment] 2022-10-27 15:18
> Why is my UI content different here?

The **Use Dataview** should be visible if you've enabled the Dataview plugin in your vault (**Settings > Community plugins**).

> It doesn't matter whether there is a difference in display effect, but it is mainly for the convenience of reading the data content.

Thank you 🙏  I've created #71 to track this issue.

**Comment by chenxin0397** [comment] 2022-10-27 15:25
Can you provide more detailed steps? More screenshots if convenient. My English is not good, there may be problems with operation and understanding😅😅😅

**Comment by chenxin0397** [comment] 2022-10-27 15:47
I seem to figure it out, because there's a little problem - the way I manage plugins is to use the template to call the plugin ID's method to start the plugin in batches.

Refer to the method here:
https://tfthacker.medium.com/improve-obsidian-startup-time-on-older-devices-with-the-faststart-script-70a6c590309f
My Dataview plugin is in the FastStart-Plugins-ShortDelay list.

The Dataview plugin is automatically opened every time the OB starts, but the problem you said still exists.
I've noticed similar issues with other plugins as well. It needs to be closed and reopened manually. The problem has been solved. Chinese forums say this is called (original state). The way I start the Dataview is not in the original state.

Above are some clues I provided. Are there any improvements to the plugin?

Anyway, with the launch method I'm using, the Dataview is available. But the plugin attached to the Dataview loses the relevant functionality

**Comment by chenxin0397** [comment] 2022-10-27 16:04
![image](https://user-images.githubusercontent.com/73974352/198341331-428125bf-9927-4e48-ab76-ccfa5a4bbb1a.png)
![image](https://user-images.githubusercontent.com/73974352/198341464-a76ffa99-352c-4f21-ba4b-e4f14c77398c.png)

**Comment by jsmm** [comment] 2022-11-20 13:14
Hi. I think the error I get is related to the one in this thread. YAMLParseError: Implicit map keys need to be followed by map values at line 4, column 1: tags   - lectura ^^^^^^^

I can't understand the message nor find the offending file(s). Tags are written in YAML front matter in new lines after two spaces and hyphen, as in:

tags:
  - lectura
  - informática

Thanks for sharing your plugin and help.

**Comment by marcusolsson** [comment] 2023-01-03 13:26
Closing in favor of #173.

**Closed by marcusolsson** 2023-01-03 13:26 UTC
Labels: triage/duplicate, kind/feature, area/datasource/dataview
