### ISSUE TITLE
Make dataview projects editable

### ISSUE THREAD

**Issue by MaxwellWibert** [marcusolsson/obsidian-projects#672] opened 2023-09-07 23:55 UTC
### What would you like to be added?

Pretty self explanatory feature request. Currently all dataview projects are read-only. I have read other issues where @marcusolsson has stated this is due to a technical limitation, however, I believe this obstacle can be overcome with the MetaEdit plugin (https://github.com/chhoumann/MetaEdit). This plugin has an API that allows you to programmatically add and update metadata to notes. Here's how I propose to do that:

First, you would obviously need to import the MetaEdit into the relevant file:

```js
const {update} = this.app.plugins.plugins["metaedit"].api;
```

Then, for example, to process when a user drags a card representing document `doc` to column `A` (when columns are determined according to property `X`), you could put  `update(X, B, doc)` inside the body of the event handler for dropping the card.

### Why is this needed?

This is a great plugin, but without dataview queries, there simply isn't enough flexibility to match my organizational style. I expect many share this problem. My use case is I would like to get my tasks from the following DQL query:

```
TABLE status as "Status",
from #task
where !contains(tags, "archive")
```
That is, i'd like to pull all of my notes with a "task" tag, and exclude those which contain an "archive" tag. Without this, I can't show all the tasks from across my vault without either deleting old tasks (can't do, need for reference) or without the old tasks cluttering up my project views. If the project is readonly however, it totally gunks any workflow that depends on that project.

To me it seems like this one problem is singularly and deeply obtrusive to the flexibility and usability of what would otherwise be my favorite plugin of all time.

***EDIT*** having just read over the above issue, I realize my comments could be read as having a tone problem. For what it's worth, I want to express my utmost gratitude to @marcusolsson for his wonderful contribution to the obsidian community. Moreover, I appreciate that he has done for free in his spare time, offering us mortals the gift of organizational bliss at no cost.

**Comment by MaxwellWibert** [comment] 2023-09-08 00:07
The MetaEdit plugin is, by the way, what the maintainer(s) of DataView recommend for updating metadata on documents in a DataView workflow

**Comment by Acylation** [comment] 2023-09-08 02:02
Yeah I also noticed that recenty. We can identify the record by the `path` field, but the implement needs investigation. Projects itself also has an editor, it's possible to vendor the features provided by MetaEdit api. (See #587 for the request to expose Projects plugin's editor)

And as for your specific workflow, it could partly be solved by setting better filters for tags. #669

**Comment by MaxwellWibert** [comment] 2023-09-08 02:44
> And as for your specific workflow, it could partly be solved by setting better filters for tags. #669

By this, do you mean there's something different that I could do as a user? Or that my organizational style would be viable in projects if the feature request you linked were implemented?

**Comment by Acylation** [comment] 2023-09-08 02:48
Need to implement I mean lol. A better filter for list would possibly meets your need, and satisfy many tag users.

**Comment by MaxwellWibert** [comment] 2023-09-08 05:40
Having just looked a bit closer at the source, it's not clear to me why DataView's readonly nature precludes the possibility of creating and updating records and their associated notes via other means. If I understand correctly, the dataview query call hands us a table whose table rows are notes, and whose table data entries are metadata props of those notes. As long as the note metadata can uniquely identify the note (say through the path, as @Acylation mentioned) we should be able to query the note's text through Obsidian's API, parse the frontmatter from that text, and update it according to the user's UI interactions ( either through Project's internal mechanisms or a MetaEdit api). Perhaps @marcusolsson could shed some light on the barriers to this approach that I'm failing to see.

I believe it may be hard to guarantee that a note created from a given record may not show up in future calls of the project's DataView query. This issue doesn't have an obvious fix to me. Unlike the changes @Acylation is proposing in #646, since DQL is so flexible that we have little choice but to treat calls to DataView as a black box. I don't see why this should prevent us from updating existing notes, though.

**Comment by Acylation** [comment] 2023-09-15 10:44
While I haven’t personally utilized Dataview, I understand that users may favor querying inline metadata, such as `field:: value`. Determining the appropriate location for our responses can be challenging. This is my current understanding. If there’s any information that I might be missing, I welcome your input.

**Comment by MaxwellWibert** [comment] 2023-09-19 05:17
You make a an interesting point. I use dataview here and there, but I don't really make much use of inline metadata, so I can't speak to the utility of that feature. In any case, I don't believe this should pose an inconquerable problem for implementation. Instead of manually parsing up the frontmatter, we could instead lookup the document metadata from Obsidian's metadata cache, no? The inline metadata should be accessible just the same as frontmatter metadata. Then if we don't find the metadata we're looking for, we can just update the frontmatter to include that value.  DataView (or maybe just obsidian) seems to handle collisions between frontmatter and inline metadata pretty gracefully. I just now tested to see what would happen in a few edge cases: 

## case 1: shared key between front and inline, no value overlap:
Dataview seems to just put all the values from both metadata definitions into a flat container. i.e if I have:
```yaml
tags: 
- memes
```
out front and `tags:: moreMemes` in the body, I just end up getting both `memes` and `moreMemes`  packaged together when I run the query:
```Dataview
TABLE tags
FROM #memes
```

## case 2: shared key between front and inline, some value overlap:
In cases where I get the same value inside some key which is defined both in front and inline, it appears to not duplicate the readout.  For example if I change the line `tags:: moreMemes` to `tags:: memes`, when I run the same Dataview query, I will only get one row for that markdown document. Inside of the row for that document, I will only get the `#memes` tag once within that row.

**Comment by m-beau** [comment] 2023-09-20 10:54
I would like to note that the metadata-menu plugin also manages to edit inline key::value fields seamlessly (I prefer it over metaedit to be able to edit fields directly from my dataview tables): https://github.com/mdelobelle/metadatamenu

**Comment by marcusolsson** [comment] 2023-10-04 10:08
Hey! It seems like this is a duplicate of https://github.com/marcusolsson/obsidian-projects/issues/173

Indeed, it's the inline attributes that's the tricky part here. Especially in combination with frontmatter. The tricky thing is that, AFAIK, there's no way to determine whether a field is frontmatter or inline attribute from the Dataview API query.

Regarding implementing this, I shared some design challenges in https://github.com/marcusolsson/obsidian-projects/issues/173#issuecomment-1400080192.

The devil's in the details here. I'd welcome an issue that outlines how a "Metadata Engine" for Projects would work, where we iteratively address the challenges until we have a stable implementation.

**Comment by Acylation** [comment] 2023-10-04 14:25
Closing as a duplicate of #173 . Thanks for revealing the previous thread.

Further discussions are warmly welcomed. I will also share my thoughts on back there.

**Closed by Acylation** 2023-10-04 14:25 UTC
Labels: kind/feature, area/datasource/dataview, triage/needs-investigation
