### ISSUE TITLE
Metadata field not recognized as list

### ISSUE THREAD

**Issue by MKDJr** [marcusolsson/obsidian-projects#119] opened 2022-11-09 04:24 UTC
### What happened?

The list of values for a key does not appear in table view.

This is the relevant metadata for the file:
![image](https://user-images.githubusercontent.com/61061178/200737107-214cdb08-380b-4714-9406-7b4d0d6b6003.png)

This is the row for the same file:
![image](https://user-images.githubusercontent.com/61061178/200737381-5a025c2f-d9fb-405d-965a-356774793562.png)

The entry for "Race" does not appear.

### What did you expect to happen?

The metadata value in the table view is the same as the one listed in the note.

### How can we reproduce it (as minimally and precisely as possible)?

Create a note with a metadata key that has multiple values formatted in a bulleted list.

### Anything else we need to know?

Removing the quotes and brackets did not seem to help.

Dataview is able to render the value:
![image](https://user-images.githubusercontent.com/61061178/200738275-54570973-3624-49be-976f-fe24e93fc97b.png)

Thank you Marcus :heart:

### Plugin version

1.0.1

### Obsidian version

1.0.3

### OS

Windows

**Comment by marcusolsson** [comment] 2022-11-09 07:51
This typically happens when multiple field types are detected for a given property. If so, it sounds like a duplicate of #71.

**Comment by MKDJr** [comment] 2022-11-10 20:34
I think that you are right. Thanks for letting me know!

**Closed** 2022-11-10 20:51 UTC
Labels: kind/bug, triage/duplicate
