### ISSUE TITLE
inline fields support

### ISSUE THREAD

**Issue by smkbhd2018** [marcusolsson/obsidian-projects#179] opened 2022-11-21 04:30 UTC
### What would you like to be added?

thank you for your plugin, it is really great🎉🎉

one of my problem that i really think is good to support is:
supporting inline-fields beside the YAML header
the plugins db folder & dataview(raw dataview without other plugins) support it and works ok with it but not projects plugin

why i think it is really good and why i use inline-fileds instead of yaml header:
- inline field let you add tag value for anything other than tag
	- for example i have a property called "status" as inline field and i have 3 values for it  "Status/Done","Status/ToDo","Status/Doing" you can enter :
	  Status:: #Status/Done 
	  for a file as inline-field but not in YAML header
		  -  What is the point of using tags?
			  1. it supports autofill in obsidian
			  2. you can see list of all tags in right panel when ever you are in obsidian
			  3. it supports parent and child for tags that lets you keep it clean
			  4. searching through tags is also very easier in obsidian search
			  5. tags are part of obsidian system that is supported in most other parts (like graph filter and search) that makes it really easy to have them
			  6. you can make them look nicer with Css (color them, change the name that they appears in view,...)

I also adde pictures to show some of points about using tags

I hope that this makes it obviouse that supporting inline-fields why is really good feature.
thank you man✨✨✨

![image](https://user-images.githubusercontent.com/65432701/202965804-63f7d28e-f3a3-4b7e-ae06-187cdc0ecdd4.png)

![2022-11-21 07_55_55-Window](https://user-images.githubusercontent.com/65432701/202965670-3a61f63b-6025-4a24-bac1-16ad398d642e.png)
![2022-11-21 07_55_41-Window](https://user-images.githubusercontent.com/65432701/202965682-a77d21d1-8622-40c4-b847-05f8e89c9456.png)
![2022-11-21 07_55_37-Window](https://user-images.githubusercontent.com/65432701/202965686-bc637cb5-d3a7-4651-8f05-5e61eb8c4ab0.png)
![2022-11-21 07_53_59-Window](https://user-images.githubusercontent.com/65432701/202965690-b180cd46-85f0-4f3e-bc2a-c1b66f398100.png)
![2022-11-21 07_53_39-Window](https://user-images.githubusercontent.com/65432701/202965695-9969e5a7-1509-40fd-817b-1421c53c16fd.png)

### Why is this needed?

thank you for your plugin, it is really great🎉🎉

one of my problem that i really think is good to support is:
supporting inline-fields beside the YAML header
the plugins db folder & dataview(raw dataview without other plugins) support it and works ok with it but not projects plugin

why i think it is really good and why i use inline-fileds instead of yaml header:
- inline field let you add tag value for anything other than tag
	- for example i have a property called "status" as inline field and i have 3 values for it  "Status/Done","Status/ToDo","Status/Doing" you can enter :
	  Status:: #Status/Done 
	  for a file as inline-field but not in YAML header
		  -  What is the point of using tags?
			  1. it supports autofill in obsidian
			  2. you can see list of all tags in right panel when ever you are in obsidian
			  3. it supports parent and child for tags that lets you keep it clean
			  4. searching through tags is also very easier in obsidian search
			  5. tags are part of obsidian system that is supported in most other parts (like graph filter and search) that makes it really easy to have them
			  6. you can make them look nicer with Css (color them, change the name that they appears in view,...)

I also adde pictures to show some of points about using tags

I hope that this makes it obviouse that supporting inline-fields why is really good feature.
thank you man✨✨✨

![image](https://user-images.githubusercontent.com/65432701/202965804-63f7d28e-f3a3-4b7e-ae06-187cdc0ecdd4.png)

![2022-11-21 07_55_55-Window](https://user-images.githubusercontent.com/65432701/202965670-3a61f63b-6025-4a24-bac1-16ad398d642e.png)
![2022-11-21 07_55_41-Window](https://user-images.githubusercontent.com/65432701/202965682-a77d21d1-8622-40c4-b847-05f8e89c9456.png)
![2022-11-21 07_55_37-Window](https://user-images.githubusercontent.com/65432701/202965686-bc637cb5-d3a7-4651-8f05-5e61eb8c4ab0.png)
![2022-11-21 07_53_59-Window](https://user-images.githubusercontent.com/65432701/202965690-b180cd46-85f0-4f3e-bc2a-c1b66f398100.png)
![2022-11-21 07_53_39-Window](https://user-images.githubusercontent.com/65432701/202965695-9969e5a7-1509-40fd-817b-1421c53c16fd.png)

**Comment by marcusolsson** [comment] 2022-11-21 13:25
Closing this as a duplicate of #173. Let me know if I got it wrong.

**Closed by marcusolsson** 2022-11-21 13:25 UTC
Labels: kind/feature, needs-triage
