### ISSUE TITLE
Add filter function

### ISSUE THREAD

**Issue by library0012** [marcusolsson/obsidian-projects#104] opened 2022-11-06 12:45 UTC
### What would you like to be added?

Would you like to add filter function in the plugin? 

So we can filter notes just in the table view without opening the settings to change the Query code

### Why is this needed?

Because of  too many tags and notes in one project，when I want to search for notes with a specific tag，I have to open the projects' setting to change the Query.  It's a quite unconvenient. 
  
It would be better if we add a filter function.

**Comment by marcusolsson** [comment] 2022-11-06 15:00
Duplicate of #80.

**Comment by marcusolsson** [comment] 2022-11-06 15:03
Closing in favor of existing issue. Feel free to add your suggestions to it!

**Closed** 2022-11-06 15:03 UTC
Labels: triage/duplicate, kind/feature
